### ISSUE TITLE
Bulding with WLA v10.2 or later produces a non-matching ROM

### ISSUE THREAD

**Issue by Strugglemeat** [lhsazevedo/akmw#7]
```
Compiling
Linking
tmp/baserom_rev0.o: MEM_INSERT: Overwrite at $7ffa (old $00 new $0d).
   ^ Writing SMS/GG ROM checksum bytes
tmp/baserom_rev0.o: MEM_INSERT: Overwrite at $7ffb (old $00 new $1a).
   ^ Writing SMS/GG ROM checksum bytes
tmp/baserom_rev1.o: MEM_INSERT: Overwrite at $7ffa (old $00 new $c4).
   ^ Writing SMS/GG ROM checksum bytes
tmp/baserom_rev1.o: MEM_INSERT: Overwrite at $7ffb (old $00 new $25).
   ^ Writing SMS/GG ROM checksum bytes
REV0 Diff :/
REV1 Diff :/

```

**Comment by lhsazevedo** [comment]
The compiler is just letting us know that some bytes were overwritten, but this is already expected in this case. See the latest build log, it is passing: https://github.com/lhsazevedo/akmw/runs/7593530172?check_suite_focus=true#step:5:15

We intentionally fill the two bytes at $7ffa and $7ffb with zeros as WLA-DX will place the ROM checksum in there:
https://github.com/lhsazevedo/akmw/blob/ed440d053b8c21ae8e886f953fdbf5db64d72c96/src/baserom.asm#L5061-L5066

https://github.com/lhsazevedo/akmw/blob/ed440d053b8c21ae8e886f953fdbf5db64d72c96/src/header.asm#L1-L18

It seems that you built the ROMs successfully, but they differ from the original one. Did you modify the sources?

**Comment by Strugglemeat** [comment]
no, I didn't modify the sources at all. If I got those warnings but the sha1 matched, then I wouldn't raise an issue.
the ROM in build/ boots OK but crashes when referencing Port_VDPAddress

**Comment by lhsazevedo** [comment]
I decided to try a newer WLA-DX version and it turns out that this issue appeared in v10.2. Version 10.1 produces matching ROMs.

Thanks for reporting this. Now we need to find out whether its a bug in WLA or a breaking change.

**Comment by lhsazevedo** [comment]
Using git bisect I was able to identify this commit as the first one that produces a non-matching build: https://github.com/vhelin/wla-dx/commit/eb67746e7511d91dc9616aecb12ecad828e7473e

@vhelin Just pinging you as may spot the problem faster if it is in my side

**Comment by vhelin** [comment]
I don't see a problem in that commit, but it could be elsewhere, not on the displayed lines.

I could change to code touched in that commit, to make the same thing, but more robust (and a little bit slower). But my "fix" will go into v10.3a (the latest sources in GitHub) - can you test with that?

**Comment by vhelin** [comment]
> If I got those warnings but the sha1 matched, then I wouldn't raise an issue.

So with WLA DX v10.2 the sha1 matches with the ROM assembled using WLA DX v10.1 (they are identical?) but WLA DX v10.2 assembled doesn't work?

**Comment by lhsazevedo** [comment]
> But my "fix" will go into v10.3a (the latest sources in GitHub) - can you test with that?

Sure. So, latest sources hangs during "Pass 1...". I could try some debugging later tonight to find out what function is freezing. For now: 
- https://github.com/vhelin/wla-dx/commit/eb67746e7511d91dc9616aecb12ecad828e7473e: First commit that produces a non-matching build
- https://github.com/vhelin/wla-dx/commit/5889312d5dac927a1a5a3da1175abb6dee5560b9: First commit that hangs during "Pass 1..."

> So with WLA DX v10.2 the sha1 matches with the ROM assembled using WLA DX v10.1 (they are identical?) but WLA DX v10.2 assembled doesn't work?

No. ROMs built with v10.1 or earlier are correct (match the expected sha1 of the original ROM).
ROMs built with v10.2 or later doesn't match the expected sha1.

I'll keep investigating

**Comment by vhelin** [comment]
With the latest WLA DX sources the assembler seems to have trouble with this:

    .IFDEF _REV1

(in baserom.asm). I'll dig deeper...

**Comment by vhelin** [comment]
I think I got hanging "Pass 1..." fixed, give me a few minutes...

**Comment by vhelin** [comment]
Ok, the "Pass 1..." hang should be fixed now. Any luck with the latest sources now?

**Comment by lhsazevedo** [comment]
Yup, no more hanging \o/.
The ROM still not matching though, but there's no need to rush. I can use v10.1 for now.

**Comment by vhelin** [comment]
I have a hunch that definitions like this are broken 

SMALL_MONEY_BAG_VALUE = $01 $00 $00 ; 100

by https://github.com/vhelin/wla-dx/commit/eb67746e7511d91dc9616aecb12ecad828e7473e ... I have to admit that I didn't remember WLA could handle such .DEFINEs and that they'd be coded internally into strings...

**Comment by vhelin** [comment]
Yeah, it seems I need to reverse that commit. :P

**Comment by vhelin** [comment]
If you use the latest WLA DX sources (v10.3a) building this project might work again. At least I was able to play the game...

![image](https://user-images.githubusercontent.com/6417746/183512683-786252ae-f77b-4a13-8576-571f812848ff.png)

**Comment by lhsazevedo** [comment]
Awesome!
```
REV0 Ok!
REV1 Ok!
```
Thanks for the supa fast fix. And have fun punching monsters and rocks :fist_oncoming:

**Comment by lhsazevedo** [comment]
@Strugglemeat So just stay in v10.1 for now while v10.3 isn't released. Or build WLA from the latest sources.
